/**
 * Crossword - Clues Database
 * 180+ entries with ES/EN/EU translations.
 * word: UPPERCASE A-Z only (no accents, no Ñ)
 * display: lowercase with proper accents for UI display
 */

const CW_CLUES = [
    // ── ANIMALES ──────────────────────────────────────────────
    { word: 'GATO', display: 'gato', category: 'animales', emoji: '🐱',
      es: { clue: 'Felino doméstico que maúlla' },
      en: { clue: 'Domestic feline that meows' },
      eu: { clue: 'Etxeko felino maularia' } },
    { word: 'PERRO', display: 'perro', category: 'animales', emoji: '🐶',
      es: { clue: 'Fiel compañero del ser humano' },
      en: { clue: 'Loyal companion of humans' },
      eu: { clue: 'Gizakiaren lagun leiala' } },
    { word: 'LEON', display: 'león', category: 'animales', emoji: '🦁',
      es: { clue: 'Rey de la sabana africana' },
      en: { clue: 'King of the African savanna' },
      eu: { clue: 'Afrikako sabanaren errege' } },
    { word: 'TIGRE', display: 'tigre', category: 'animales', emoji: '🐯',
      es: { clue: 'Gran felino rayado de Asia' },
      en: { clue: 'Large striped Asian feline' },
      eu: { clue: 'Asiako felino lerroduna' } },
    { word: 'ELEFANTE', display: 'elefante', category: 'animales', emoji: '🐘',
      es: { clue: 'El mayor animal terrestre' },
      en: { clue: 'The largest land animal' },
      eu: { clue: 'Lurreko animalia handiena' } },
    { word: 'BALLENA', display: 'ballena', category: 'animales', emoji: '🐳',
      es: { clue: 'Mamífero marino más grande del mundo' },
      en: { clue: 'Largest marine mammal' },
      eu: { clue: 'Munduko ugaztun marinerik handiena' } },
    { word: 'AGUILA', display: 'águila', category: 'animales', emoji: '🦅',
      es: { clue: 'Ave rapaz de gran envergadura' },
      en: { clue: 'Large bird of prey' },
      eu: { clue: 'Hegazti arrapari handia' } },
    { word: 'SERPIENTE', display: 'serpiente', category: 'animales', emoji: '🐍',
      es: { clue: 'Reptil sin patas que repta' },
      en: { clue: 'Legless reptile that slithers' },
      eu: { clue: 'Hankarik gabeko narrastia' } },
    { word: 'COCODRILO', display: 'cocodrilo', category: 'animales', emoji: '🐊',
      es: { clue: 'Reptil de río con mandíbulas poderosas' },
      en: { clue: 'River reptile with powerful jaws' },
      eu: { clue: 'Masaila indartsuko ibaiko narrastia' } },
    { word: 'DELFIN', display: 'delfín', category: 'animales', emoji: '🐬',
      es: { clue: 'Mamífero marino muy inteligente' },
      en: { clue: 'Very intelligent marine mammal' },
      eu: { clue: 'Itsas ugaztun oso adimenduna' } },
    { word: 'GORILA', display: 'gorila', category: 'animales', emoji: '🦍',
      es: { clue: 'El mayor de los primates' },
      en: { clue: 'The largest primate' },
      eu: { clue: 'Primateen arteko handiena' } },
    { word: 'PANDA', display: 'panda', category: 'animales', emoji: '🐼',
      es: { clue: 'Oso negro y blanco de China' },
      en: { clue: 'Black and white bear from China' },
      eu: { clue: 'Txinako beltz eta zuri hartza' } },
    { word: 'RATON', display: 'ratón', category: 'animales', emoji: '🐭',
      es: { clue: 'Pequeño roedor de cola larga' },
      en: { clue: 'Small rodent with a long tail' },
      eu: { clue: 'Buztan luzeeko karraskarri txikia' } },
    { word: 'CONEJO', display: 'conejo', category: 'animales', emoji: '🐇',
      es: { clue: 'Mamífero de largas orejas' },
      en: { clue: 'Long-eared mammal' },
      eu: { clue: 'Belarri luzeko ugaztuna' } },
    { word: 'OSO', display: 'oso', category: 'animales', emoji: '🐻',
      es: { clue: 'Gran mamífero que hiberna' },
      en: { clue: 'Large mammal that hibernates' },
      eu: { clue: 'Neguan lo egiten duen ugaztun handia' } },
    { word: 'JIRAFA', display: 'jirafa', category: 'animales', emoji: '🦒',
      es: { clue: 'Animal terrestre de cuello más largo' },
      en: { clue: 'Tallest living land animal' },
      eu: { clue: 'Lurreko animalia lepoluzeena' } },
    { word: 'HIPOPOTAMO', display: 'hipopótamo', category: 'animales', emoji: '🦛',
      es: { clue: 'Gran mamífero semiacuático africano' },
      en: { clue: 'Large semi-aquatic African mammal' },
      eu: { clue: 'Afrikako ugaztun erdi-uretiko handia' } },

    // ── GEOGRAFÍA ─────────────────────────────────────────────
    { word: 'NILO', display: 'Nilo', category: 'geografia', emoji: '🌊',
      es: { clue: 'Río más largo de África' },
      en: { clue: 'Longest river in Africa' },
      eu: { clue: 'Afrikako ibairik luzeena' } },
    { word: 'AMAZON', display: 'Amazonas', category: 'geografia', emoji: '🌳',
      es: { clue: 'Mayor río del mundo por caudal' },
      en: { clue: 'World\'s largest river by flow' },
      eu: { clue: 'Emariaren arabera munduko ibairik handiena' } },
    { word: 'EVEREST', display: 'Everest', category: 'geografia', emoji: '🏔️',
      es: { clue: 'Montaña más alta del planeta' },
      en: { clue: 'Highest mountain on Earth' },
      eu: { clue: 'Lurrazaleko mendi altuena' } },
    { word: 'SAHARA', display: 'Sahara', category: 'geografia', emoji: '🏜️',
      es: { clue: 'Desierto más caliente del mundo' },
      en: { clue: 'World\'s hottest desert' },
      eu: { clue: 'Munduko basamortu beroena' } },
    { word: 'EUROPA', display: 'Europa', category: 'geografia', emoji: '🌍',
      es: { clue: 'Continente de la Unión Europea' },
      en: { clue: 'Continent of the European Union' },
      eu: { clue: 'Europar Batasunaren kontinentea' } },
    { word: 'AFRICA', display: 'África', category: 'geografia', emoji: '🌍',
      es: { clue: 'Continente con más países del mundo' },
      en: { clue: 'Continent with the most countries' },
      eu: { clue: 'Herrialde gehien dituen kontinentea' } },
    { word: 'BRASIL', display: 'Brasil', category: 'geografia', emoji: '🇧🇷',
      es: { clue: 'País más grande de América del Sur' },
      en: { clue: 'Largest country in South America' },
      eu: { clue: 'Hego Amerikako herririk handiena' } },
    { word: 'JAPON', display: 'Japón', category: 'geografia', emoji: '🇯🇵',
      es: { clue: 'País insular del sol naciente' },
      en: { clue: 'Island nation of the rising sun' },
      eu: { clue: 'Eguzkia igotzen den uharte nazioa' } },
    { word: 'PARIS', display: 'París', category: 'geografia', emoji: '🗼',
      es: { clue: 'Capital de Francia, ciudad de la luz' },
      en: { clue: 'Capital of France, city of light' },
      eu: { clue: 'Frantziako hiriburua, argiaren hiria' } },
    { word: 'ROMA', display: 'Roma', category: 'geografia', emoji: '🏛️',
      es: { clue: 'Ciudad eterna, capital italiana' },
      en: { clue: 'Eternal city, Italian capital' },
      eu: { clue: 'Hiri eternoa, Italiako hiriburua' } },
    { word: 'ANDES', display: 'Andes', category: 'geografia', emoji: '⛰️',
      es: { clue: 'Cordillera más larga del mundo' },
      en: { clue: 'World\'s longest mountain range' },
      eu: { clue: 'Munduko mendikate luzeena' } },
    { word: 'ALPES', display: 'Alpes', category: 'geografia', emoji: '🏔️',
      es: { clue: 'Montañas que cruzan Europa central' },
      en: { clue: 'Mountains crossing central Europe' },
      eu: { clue: 'Europa erdialdetik igarotzen diren mendiak' } },
    { word: 'VOLGA', display: 'Volga', category: 'geografia', emoji: '🌊',
      es: { clue: 'Río más largo de Europa' },
      en: { clue: 'Longest river in Europe' },
      eu: { clue: 'Europako ibairik luzeena' } },
    { word: 'CARIBE', display: 'Caribe', category: 'geografia', emoji: '🏖️',
      es: { clue: 'Mar tropical de aguas cálidas' },
      en: { clue: 'Tropical sea with warm waters' },
      eu: { clue: 'Ur beroko itsaso tropikala' } },
    { word: 'TIBER', display: 'Tíber', category: 'geografia', emoji: '🌊',
      es: { clue: 'Río que atraviesa Roma' },
      en: { clue: 'River that flows through Rome' },
      eu: { clue: 'Erroma zeharkatzen duen ibaia' } },
    { word: 'GANGES', display: 'Ganges', category: 'geografia', emoji: '🌊',
      es: { clue: 'Río sagrado de la India' },
      en: { clue: 'Sacred river of India' },
      eu: { clue: 'Indiako ibai sakratua' } },

    // ── BIOLOGÍA ──────────────────────────────────────────────
    { word: 'CELULA', display: 'célula', category: 'biologia', emoji: '🔬',
      es: { clue: 'Unidad básica de la vida' },
      en: { clue: 'Basic unit of life' },
      eu: { clue: 'Bizitzaren oinarrizko unitatea' } },
    { word: 'NUCLEO', display: 'núcleo', category: 'biologia', emoji: '🔬',
      es: { clue: 'Centro de control de la célula' },
      en: { clue: 'Control center of the cell' },
      eu: { clue: 'Zelularen kontrol zentroa' } },
    { word: 'OSMOSIS', display: 'ósmosis', category: 'biologia', emoji: '💧',
      es: { clue: 'Difusión de agua a través de membrana' },
      en: { clue: 'Water diffusion through a membrane' },
      eu: { clue: 'Uraren difusioa mintze bidez' } },
    { word: 'NEURONA', display: 'neurona', category: 'biologia', emoji: '🧠',
      es: { clue: 'Célula del sistema nervioso' },
      en: { clue: 'Cell of the nervous system' },
      eu: { clue: 'Nerbio-sistemaren zelula' } },
    { word: 'ENZIMA', display: 'enzima', category: 'biologia', emoji: '🧪',
      es: { clue: 'Proteína que acelera reacciones' },
      en: { clue: 'Protein that speeds up reactions' },
      eu: { clue: 'Erreakzioak bizkortu dituen proteina' } },
    { word: 'BACTERIA', display: 'bacteria', category: 'biologia', emoji: '🦠',
      es: { clue: 'Microorganismo unicelular procariota' },
      en: { clue: 'Single-celled prokaryotic microorganism' },
      eu: { clue: 'Zelula bakarreko mikroorganismo prokariotoa' } },
    { word: 'VIRUS', display: 'virus', category: 'biologia', emoji: '🦠',
      es: { clue: 'Agente infeccioso que necesita huésped' },
      en: { clue: 'Infectious agent needing a host' },
      eu: { clue: 'Ostalariu bat behar duen infekzio-agentea' } },
    { word: 'TEJIDO', display: 'tejido', category: 'biologia', emoji: '🔬',
      es: { clue: 'Conjunto de células similares' },
      en: { clue: 'Group of similar cells' },
      eu: { clue: 'Zelula antzekoen multzoa' } },
    { word: 'PROTEINA', display: 'proteína', category: 'biologia', emoji: '🧬',
      es: { clue: 'Macromolécula esencial para el organismo' },
      en: { clue: 'Essential macromolecule for organisms' },
      eu: { clue: 'Organismorako ezinbesteko makromolekula' } },
    { word: 'VITAMINA', display: 'vitamina', category: 'biologia', emoji: '💊',
      es: { clue: 'Nutriente esencial en pequeñas cantidades' },
      en: { clue: 'Essential nutrient in small amounts' },
      eu: { clue: 'Kopuru txikietan ezinbesteko nutrientea' } },
    { word: 'FOSIL', display: 'fósil', category: 'biologia', emoji: '🦕',
      es: { clue: 'Resto petrificado de ser vivo antiguo' },
      en: { clue: 'Petrified remains of ancient life' },
      eu: { clue: 'Antzinako izaki biziaren aztarna harriztua' } },
    { word: 'EVOLUCION', display: 'evolución', category: 'biologia', emoji: '🦎',
      es: { clue: 'Cambio gradual de las especies' },
      en: { clue: 'Gradual change of species' },
      eu: { clue: 'Espezieen aldaketa pixkanakakoa' } },
    { word: 'ORGANISMO', display: 'organismo', category: 'biologia', emoji: '🌱',
      es: { clue: 'Ser vivo con funciones propias' },
      en: { clue: 'Living being with its own functions' },
      eu: { clue: 'Bere funtzioak dituen izaki bizia' } },
    { word: 'ADN', display: 'ADN', category: 'biologia', emoji: '🧬',
      es: { clue: 'Molécula portadora de información genética' },
      en: { clue: 'Molecule carrying genetic information' },
      eu: { clue: 'Informazio genetikoa darabilen molekula' } },
    { word: 'MITOSIS', display: 'mitosis', category: 'biologia', emoji: '🔬',
      es: { clue: 'División celular que produce dos células' },
      en: { clue: 'Cell division producing two cells' },
      eu: { clue: 'Bi zelula sortzen dituen zelula-zatiketa' } },

    // ── ASTRONOMÍA ────────────────────────────────────────────
    { word: 'SOL', display: 'Sol', category: 'astronomia', emoji: '☀️',
      es: { clue: 'Estrella central de nuestro sistema' },
      en: { clue: 'Central star of our solar system' },
      eu: { clue: 'Gure eguzki-sistemaren erdiko izarra' } },
    { word: 'LUNA', display: 'Luna', category: 'astronomia', emoji: '🌕',
      es: { clue: 'Satélite natural de la Tierra' },
      en: { clue: 'Natural satellite of Earth' },
      eu: { clue: 'Lurraren satelite naturala' } },
    { word: 'MARTE', display: 'Marte', category: 'astronomia', emoji: '🔴',
      es: { clue: 'Planeta rojo vecino de la Tierra' },
      en: { clue: 'Red planet neighbouring Earth' },
      eu: { clue: 'Lurraren auzoko planeta gorria' } },
    { word: 'VENUS', display: 'Venus', category: 'astronomia', emoji: '⭐',
      es: { clue: 'Planeta más caliente del sistema solar' },
      en: { clue: 'Hottest planet in the solar system' },
      eu: { clue: 'Eguzki-sistemako planeta beroena' } },
    { word: 'JUPITER', display: 'Júpiter', category: 'astronomia', emoji: '🪐',
      es: { clue: 'El planeta más grande del sistema solar' },
      en: { clue: 'The largest planet in the solar system' },
      eu: { clue: 'Eguzki-sistemako planeta handiena' } },
    { word: 'SATURNO', display: 'Saturno', category: 'astronomia', emoji: '🪐',
      es: { clue: 'Planeta con espectaculares anillos' },
      en: { clue: 'Planet with spectacular rings' },
      eu: { clue: 'Eraztun ikusgarriak dituen planeta' } },
    { word: 'COMETA', display: 'cometa', category: 'astronomia', emoji: '☄️',
      es: { clue: 'Cuerpo celeste con cola luminosa' },
      en: { clue: 'Celestial body with a luminous tail' },
      eu: { clue: 'Buztan argitsua duen zeruko gorputza' } },
    { word: 'GALAXIA', display: 'galaxia', category: 'astronomia', emoji: '🌌',
      es: { clue: 'Conjunto de miles de millones de estrellas' },
      en: { clue: 'System of billions of stars' },
      eu: { clue: 'Milaka milioi izarren sistema' } },
    { word: 'NEBULOSA', display: 'nebulosa', category: 'astronomia', emoji: '🌌',
      es: { clue: 'Nube interestelar de gas y polvo' },
      en: { clue: 'Interstellar cloud of gas and dust' },
      eu: { clue: 'Gas eta hautsezko hodei artizarra' } },
    { word: 'ECLIPSE', display: 'eclipse', category: 'astronomia', emoji: '🌑',
      es: { clue: 'Ocultación de un astro por otro' },
      en: { clue: 'Blocking of one celestial body by another' },
      eu: { clue: 'Zeruko gorputz baten beste baten atzean ezkutatzea' } },
    { word: 'ORBITA', display: 'órbita', category: 'astronomia', emoji: '🌍',
      es: { clue: 'Trayectoria de un astro alrededor de otro' },
      en: { clue: 'Path of a body around another' },
      eu: { clue: 'Gorputz batek bestearen inguruan duen ibilbidea' } },
    { word: 'COSMOS', display: 'cosmos', category: 'astronomia', emoji: '🌌',
      es: { clue: 'El universo como sistema ordenado' },
      en: { clue: 'The universe as an ordered system' },
      eu: { clue: 'Unibertsoa sistema ordenatu gisa' } },
    { word: 'METEOR', display: 'meteoro', category: 'astronomia', emoji: '☄️',
      es: { clue: 'Roca que arde al entrar en la atmósfera' },
      en: { clue: 'Rock burning on entering the atmosphere' },
      eu: { clue: 'Atmosferara sartzean erre egiten den harria' } },
    { word: 'PLUTON', display: 'Plutón', category: 'astronomia', emoji: '⚫',
      es: { clue: 'Planeta enano más allá de Neptuno' },
      en: { clue: 'Dwarf planet beyond Neptune' },
      eu: { clue: 'Neptunoren harago dagoen planeta nano' } },
    { word: 'URANO', display: 'Urano', category: 'astronomia', emoji: '🔵',
      es: { clue: 'Planeta que gira de lado' },
      en: { clue: 'Planet that rotates on its side' },
      eu: { clue: 'Alboetara biratzen den planeta' } },

    // ── HISTORIA ──────────────────────────────────────────────
    { word: 'FARAON', display: 'faraón', category: 'historia', emoji: '👑',
      es: { clue: 'Soberano del Antiguo Egipto' },
      en: { clue: 'Ruler of Ancient Egypt' },
      eu: { clue: 'Antzinako Egiptoko agintaria' } },
    { word: 'PIRAMIDE', display: 'pirámide', category: 'historia', emoji: '🔺',
      es: { clue: 'Monumento funerario egipcio' },
      en: { clue: 'Egyptian funerary monument' },
      eu: { clue: 'Egiptoar hileta-monumentua' } },
    { word: 'GLADIADOR', display: 'gladiador', category: 'historia', emoji: '⚔️',
      es: { clue: 'Luchador romano en el Coliseo' },
      en: { clue: 'Roman fighter in the Colosseum' },
      eu: { clue: 'Koloseon borrokatzen zen erromatarra' } },
    { word: 'CRUZADA', display: 'cruzada', category: 'historia', emoji: '✝️',
      es: { clue: 'Expedición militar medieval religiosa' },
      en: { clue: 'Medieval religious military expedition' },
      eu: { clue: 'Erdi Aroko espedizio militar erlijiosoa' } },
    { word: 'REPUBLICA', display: 'república', category: 'historia', emoji: '🏛️',
      es: { clue: 'Forma de gobierno sin monarca' },
      en: { clue: 'Form of government without a monarch' },
      eu: { clue: 'Monarkia gabeko gobernu-forma' } },
    { word: 'DEMOCRACIA', display: 'democracia', category: 'historia', emoji: '🗳️',
      es: { clue: 'Sistema donde el pueblo gobierna' },
      en: { clue: 'System where the people rule' },
      eu: { clue: 'Herriak gobernatzen duen sistema' } },
    { word: 'REVOLUCION', display: 'revolución', category: 'historia', emoji: '⚡',
      es: { clue: 'Cambio radical y rápido en el poder' },
      en: { clue: 'Radical and rapid change in power' },
      eu: { clue: 'Boterearen aldaketa erradikala eta azkarra' } },
    { word: 'ROMANO', display: 'romano', category: 'historia', emoji: '🏛️',
      es: { clue: 'Ciudadano del Imperio de Roma' },
      en: { clue: 'Citizen of the Roman Empire' },
      eu: { clue: 'Erromako Inperioko hiritarra' } },
    { word: 'GRIEGO', display: 'griego', category: 'historia', emoji: '🏛️',
      es: { clue: 'Habitante de la antigua Grecia' },
      en: { clue: 'Inhabitant of ancient Greece' },
      eu: { clue: 'Antzinako Grezian bizi zen pertsona' } },
    { word: 'AZTECA', display: 'azteca', category: 'historia', emoji: '🏯',
      es: { clue: 'Civilización del México antiguo' },
      en: { clue: 'Civilisation of ancient Mexico' },
      eu: { clue: 'Antzinako Mexikoko zibilizazioa' } },
    { word: 'MAYA', display: 'maya', category: 'historia', emoji: '🏯',
      es: { clue: 'Civilización prehispánica de Mesoamérica' },
      en: { clue: 'Pre-Hispanic Mesoamerican civilisation' },
      eu: { clue: 'Mesoamerikako zibilizazio prehispanikoa' } },
    { word: 'INCA', display: 'inca', category: 'historia', emoji: '🦙',
      es: { clue: 'Imperio andino de América del Sur' },
      en: { clue: 'Andean empire of South America' },
      eu: { clue: 'Hego Amerikako Andetako inperioa' } },
    { word: 'CASTILLO', display: 'castillo', category: 'historia', emoji: '🏰',
      es: { clue: 'Fortaleza medieval con torres' },
      en: { clue: 'Medieval fortress with towers' },
      eu: { clue: 'Dorreak dituen Erdi Aroko gotorlekua' } },
    { word: 'MEDIEVAL', display: 'medieval', category: 'historia', emoji: '⚔️',
      es: { clue: 'Relativo a la Edad Media' },
      en: { clue: 'Relating to the Middle Ages' },
      eu: { clue: 'Erdi Aroari dagokiona' } },
    { word: 'VIKINGO', display: 'vikingo', category: 'historia', emoji: '⚓',
      es: { clue: 'Explorador nórdico de la Edad Media' },
      en: { clue: 'Nordic explorer of the Middle Ages' },
      eu: { clue: 'Erdi Aroko nordikoen esploratzailea' } },

    // ── CULTURA ───────────────────────────────────────────────
    { word: 'PINTURA', display: 'pintura', category: 'cultura', emoji: '🎨',
      es: { clue: 'Arte visual aplicado sobre lienzo' },
      en: { clue: 'Visual art applied on canvas' },
      eu: { clue: 'Mihisean aplikatutako arte bisualak' } },
    { word: 'ESCULTURA', display: 'escultura', category: 'cultura', emoji: '🗿',
      es: { clue: 'Arte que modela formas en tres dimensiones' },
      en: { clue: 'Art that shapes three-dimensional forms' },
      eu: { clue: 'Hiru dimentsioko formak moldatzen dituen artea' } },
    { word: 'MELODIA', display: 'melodía', category: 'cultura', emoji: '🎵',
      es: { clue: 'Secuencia musical reconocible' },
      en: { clue: 'Recognisable musical sequence' },
      eu: { clue: 'Musika-segida ezagarria' } },
    { word: 'NOVELA', display: 'novela', category: 'cultura', emoji: '📚',
      es: { clue: 'Obra literaria extensa en prosa' },
      en: { clue: 'Long prose literary work' },
      eu: { clue: 'Prosazko obra literario luzea' } },
    { word: 'POEMA', display: 'poema', category: 'cultura', emoji: '📜',
      es: { clue: 'Obra literaria escrita en verso' },
      en: { clue: 'Literary work written in verse' },
      eu: { clue: 'Bertsetan idatzitako obra literarioa' } },
    { word: 'TEATRO', display: 'teatro', category: 'cultura', emoji: '🎭',
      es: { clue: 'Arte escénico interpretado en vivo' },
      en: { clue: 'Performing art presented live' },
      eu: { clue: 'Zuzenean aurkezten den arte eszearikoa' } },
    { word: 'OPERA', display: 'ópera', category: 'cultura', emoji: '🎼',
      es: { clue: 'Drama musical cantado en su totalidad' },
      en: { clue: 'Musical drama entirely sung' },
      eu: { clue: 'Guztia abesten den drama musikala' } },
    { word: 'BALLET', display: 'ballet', category: 'cultura', emoji: '🩰',
      es: { clue: 'Danza clásica de gran elegancia' },
      en: { clue: 'Classical dance of great elegance' },
      eu: { clue: 'Elegantzia handiko dantza klasikoa' } },
    { word: 'GUITARRA', display: 'guitarra', category: 'cultura', emoji: '🎸',
      es: { clue: 'Instrumento de cuerda pulsada' },
      en: { clue: 'Plucked string instrument' },
      eu: { clue: 'Haria tiratutako musika-tresna' } },
    { word: 'SINFONIA', display: 'sinfonía', category: 'cultura', emoji: '🎻',
      es: { clue: 'Composición orquestal de gran escala' },
      en: { clue: 'Large-scale orchestral composition' },
      eu: { clue: 'Eskala handiko orkestra-konposizioa' } },
    { word: 'ACUARELA', display: 'acuarela', category: 'cultura', emoji: '🎨',
      es: { clue: 'Pintura transparente a base de agua' },
      en: { clue: 'Transparent water-based paint' },
      eu: { clue: 'Uretan oinarritutako pintura gardena' } },
    { word: 'SONETO', display: 'soneto', category: 'cultura', emoji: '📜',
      es: { clue: 'Poema de 14 versos con rima fija' },
      en: { clue: '14-line poem with fixed rhyme' },
      eu: { clue: 'Errimaerrikoa duten 14 bertso-lerrotako poema' } },
    { word: 'ESTROFA', display: 'estrofa', category: 'cultura', emoji: '📝',
      es: { clue: 'Grupo de versos de un poema' },
      en: { clue: 'Group of verses in a poem' },
      eu: { clue: 'Poema bateko bertsoen taldea' } },
    { word: 'ARMONIA', display: 'armonía', category: 'cultura', emoji: '🎵',
      es: { clue: 'Combinación agradable de sonidos musicales' },
      en: { clue: 'Pleasant combination of musical sounds' },
      eu: { clue: 'Musika-soinuen konbinazio atsegina' } },
    { word: 'FOTOGRAFIA', display: 'fotografía', category: 'cultura', emoji: '📷',
      es: { clue: 'Arte de capturar imágenes con luz' },
      en: { clue: 'Art of capturing images with light' },
      eu: { clue: 'Argiz irudiak hartzeko artea' } },

    // ── DEPORTES ──────────────────────────────────────────────
    { word: 'FUTBOL', display: 'fútbol', category: 'deportes', emoji: '⚽',
      es: { clue: 'Deporte de equipo con balón redondo' },
      en: { clue: 'Team sport with a round ball' },
      eu: { clue: 'Baloi biribila duen taldekako kirola' } },
    { word: 'NATACION', display: 'natación', category: 'deportes', emoji: '🏊',
      es: { clue: 'Deporte que se practica en el agua' },
      en: { clue: 'Sport practised in water' },
      eu: { clue: 'Uretan praktikatzen den kirola' } },
    { word: 'ATLETISMO', display: 'atletismo', category: 'deportes', emoji: '🏃',
      es: { clue: 'Deporte de correr, saltar y lanzar' },
      en: { clue: 'Sport of running, jumping and throwing' },
      eu: { clue: 'Korrika, jauzi eta jaurtitzearen kirola' } },
    { word: 'CICLISMO', display: 'ciclismo', category: 'deportes', emoji: '🚴',
      es: { clue: 'Deporte sobre bicicleta' },
      en: { clue: 'Sport on a bicycle' },
      eu: { clue: 'Bizikletan egiten den kirola' } },
    { word: 'TENIS', display: 'tenis', category: 'deportes', emoji: '🎾',
      es: { clue: 'Deporte de raqueta y pelota amarilla' },
      en: { clue: 'Sport with racket and yellow ball' },
      eu: { clue: 'Erraketa eta pilota horiarekiko kirola' } },
    { word: 'BOXEO', display: 'boxeo', category: 'deportes', emoji: '🥊',
      es: { clue: 'Deporte de combate con los puños' },
      en: { clue: 'Combat sport using the fists' },
      eu: { clue: 'Ukabilak erabiliz borrokatzen den kirola' } },
    { word: 'VOLEIBOL', display: 'voleibol', category: 'deportes', emoji: '🏐',
      es: { clue: 'Deporte en que se golpea el balón sobre la red' },
      en: { clue: 'Sport where the ball is hit over a net' },
      eu: { clue: 'Baloia sarean gainetik kolpatzen den kirola' } },
    { word: 'RUGBY', display: 'rugby', category: 'deportes', emoji: '🏉',
      es: { clue: 'Deporte de contacto con balón ovalado' },
      en: { clue: 'Contact sport with an oval ball' },
      eu: { clue: 'Baloi obalatuarekin harremanetan egiten den kirola' } },
    { word: 'ESGRIMA', display: 'esgrima', category: 'deportes', emoji: '🤺',
      es: { clue: 'Deporte de combate con espada' },
      en: { clue: 'Combat sport using a sword' },
      eu: { clue: 'Ezpata erabiliz borrokatzen den kirola' } },
    { word: 'JUDO', display: 'judo', category: 'deportes', emoji: '🥋',
      es: { clue: 'Arte marcial japonés de lanzamientos' },
      en: { clue: 'Japanese martial art of throws' },
      eu: { clue: 'Jaurtiketen japoniako arte martzial' } },
    { word: 'ESCALADA', display: 'escalada', category: 'deportes', emoji: '🧗',
      es: { clue: 'Deporte de ascenso en roca o muro' },
      en: { clue: 'Sport of climbing rock or wall' },
      eu: { clue: 'Harkaitz edo horma igotzearen kirola' } },
    { word: 'ESQUI', display: 'esquí', category: 'deportes', emoji: '⛷️',
      es: { clue: 'Deporte de deslizarse por la nieve' },
      en: { clue: 'Sport of sliding on snow' },
      eu: { clue: 'Elurretik irristatzeko kirola' } },
    { word: 'MARATON', display: 'maratón', category: 'deportes', emoji: '🏅',
      es: { clue: 'Carrera pedestre de 42 kilómetros' },
      en: { clue: 'Foot race of 42 kilometres' },
      eu: { clue: '42 kilometroko oinezko lasterketa' } },
    { word: 'SPRINT', display: 'sprint', category: 'deportes', emoji: '💨',
      es: { clue: 'Carrera de velocidad máxima corta' },
      en: { clue: 'Short maximum-speed race' },
      eu: { clue: 'Abiadura maximoko lasterketa laburra' } },
    { word: 'KARATE', display: 'karate', category: 'deportes', emoji: '🥋',
      es: { clue: 'Arte marcial japonés de golpes' },
      en: { clue: 'Japanese martial art using strikes' },
      eu: { clue: 'Kolpeak darabiltzaten japoniako arte martzial' } },

    // ── CIENCIA ───────────────────────────────────────────────
    { word: 'GRAVITACION', display: 'gravitación', category: 'ciencia', emoji: '🍎',
      es: { clue: 'Fuerza de atracción entre masas' },
      en: { clue: 'Attractive force between masses' },
      eu: { clue: 'Massen arteko erakarpen-indarra' } },
    { word: 'ENERGIA', display: 'energía', category: 'ciencia', emoji: '⚡',
      es: { clue: 'Capacidad de realizar trabajo' },
      en: { clue: 'Ability to do work' },
      eu: { clue: 'Lana egiteko gaitasuna' } },
    { word: 'ATOMO', display: 'átomo', category: 'ciencia', emoji: '⚛️',
      es: { clue: 'Partícula mínima de un elemento' },
      en: { clue: 'Smallest particle of an element' },
      eu: { clue: 'Elementu baten partikularik txikiena' } },
    { word: 'ELECTRON', display: 'electrón', category: 'ciencia', emoji: '⚛️',
      es: { clue: 'Partícula atómica de carga negativa' },
      en: { clue: 'Atomic particle with negative charge' },
      eu: { clue: 'Karga negatiboko partikula atomikoa' } },
    { word: 'NEUTRON', display: 'neutrón', category: 'ciencia', emoji: '⚛️',
      es: { clue: 'Partícula atómica sin carga eléctrica' },
      en: { clue: 'Atomic particle with no electric charge' },
      eu: { clue: 'Karga elektriko gabekoa partikula atomikoa' } },
    { word: 'PROTON', display: 'protón', category: 'ciencia', emoji: '⚛️',
      es: { clue: 'Partícula atómica de carga positiva' },
      en: { clue: 'Atomic particle with positive charge' },
      eu: { clue: 'Karga positiboko partikula atomikoa' } },
    { word: 'MAGNETISMO', display: 'magnetismo', category: 'ciencia', emoji: '🧲',
      es: { clue: 'Fenómeno de atracción del imán' },
      en: { clue: 'Phenomenon of magnet attraction' },
      eu: { clue: 'Imanaren erakarpen fenomenoa' } },
    { word: 'ELECTRICIDAD', display: 'electricidad', category: 'ciencia', emoji: '⚡',
      es: { clue: 'Flujo de electrones en un conductor' },
      en: { clue: 'Flow of electrons in a conductor' },
      eu: { clue: 'Eroale batean elektroi-fluxua' } },
    { word: 'QUIMICA', display: 'química', category: 'ciencia', emoji: '🧪',
      es: { clue: 'Ciencia que estudia la materia y sus cambios' },
      en: { clue: 'Science studying matter and its changes' },
      eu: { clue: 'Materia eta bere aldaketak aztertzen dituen zientzia' } },
    { word: 'FISICA', display: 'física', category: 'ciencia', emoji: '⚛️',
      es: { clue: 'Ciencia de la materia, energía y fuerzas' },
      en: { clue: 'Science of matter, energy and forces' },
      eu: { clue: 'Materia, energia eta indarren zientzia' } },
    { word: 'CALOR', display: 'calor', category: 'ciencia', emoji: '🌡️',
      es: { clue: 'Energía que se transfiere por temperatura' },
      en: { clue: 'Energy transferred by temperature' },
      eu: { clue: 'Tenperaturaren bidez transferitzen den energia' } },
    { word: 'PRESION', display: 'presión', category: 'ciencia', emoji: '🔩',
      es: { clue: 'Fuerza ejercida por unidad de área' },
      en: { clue: 'Force exerted per unit area' },
      eu: { clue: 'Azalera-unitateko indar aplikatua' } },
    { word: 'VELOCIDAD', display: 'velocidad', category: 'ciencia', emoji: '💨',
      es: { clue: 'Distancia recorrida por unidad de tiempo' },
      en: { clue: 'Distance covered per unit of time' },
      eu: { clue: 'Denbora-unitateko distantzia egindakoa' } },
    { word: 'INERCIA', display: 'inercia', category: 'ciencia', emoji: '🔄',
      es: { clue: 'Tendencia de los cuerpos a mantener su estado' },
      en: { clue: 'Tendency of bodies to maintain their state' },
      eu: { clue: 'Gorputzek egoera mantentzeko joera' } },
    { word: 'ONDAS', display: 'ondas', category: 'ciencia', emoji: '🌊',
      es: { clue: 'Perturbación que se propaga en un medio' },
      en: { clue: 'Disturbance propagating through a medium' },
      eu: { clue: 'Bitarteko batean hedatzen den perturbazio' } },

    // ── TECNOLOGÍA ────────────────────────────────────────────
    { word: 'ORDENADOR', display: 'ordenador', category: 'tecnologia', emoji: '💻',
      es: { clue: 'Máquina electrónica de procesamiento de datos' },
      en: { clue: 'Electronic data processing machine' },
      eu: { clue: 'Datuak prozesatzeko makina elektronikoa' } },
    { word: 'INTERNET', display: 'internet', category: 'tecnologia', emoji: '🌐',
      es: { clue: 'Red global de computadoras conectadas' },
      en: { clue: 'Global network of connected computers' },
      eu: { clue: 'Ordenagailuak lotutako sare globalaren' } },
    { word: 'ROBOT', display: 'robot', category: 'tecnologia', emoji: '🤖',
      es: { clue: 'Máquina que realiza tareas automáticamente' },
      en: { clue: 'Machine that performs tasks automatically' },
      eu: { clue: 'Zereginak automatikoki egiten dituen makina' } },
    { word: 'PROGRAMA', display: 'programa', category: 'tecnologia', emoji: '💾',
      es: { clue: 'Conjunto de instrucciones para un ordenador' },
      en: { clue: 'Set of instructions for a computer' },
      eu: { clue: 'Ordenagailu baterako instrukzio multzoa' } },
    { word: 'ALGORITMO', display: 'algoritmo', category: 'tecnologia', emoji: '🔢',
      es: { clue: 'Secuencia de pasos para resolver un problema' },
      en: { clue: 'Sequence of steps to solve a problem' },
      eu: { clue: 'Arazo bat konpontzeko urrats-segida' } },
    { word: 'PIXEL', display: 'píxel', category: 'tecnologia', emoji: '🖥️',
      es: { clue: 'Unidad mínima de una imagen digital' },
      en: { clue: 'Minimum unit of a digital image' },
      eu: { clue: 'Irudi digital baten unitate txikiena' } },
    { word: 'SERVIDOR', display: 'servidor', category: 'tecnologia', emoji: '🖥️',
      es: { clue: 'Computadora que provee servicios en red' },
      en: { clue: 'Computer providing network services' },
      eu: { clue: 'Sareko zerbitzuak ematen dituen ordenagailua' } },
    { word: 'DATOS', display: 'datos', category: 'tecnologia', emoji: '📊',
      es: { clue: 'Información procesable por un sistema' },
      en: { clue: 'Information processable by a system' },
      eu: { clue: 'Sistema batek prozesa dezakeen informazioa' } },
    { word: 'CODIGO', display: 'código', category: 'tecnologia', emoji: '💻',
      es: { clue: 'Conjunto de instrucciones escritas para software' },
      en: { clue: 'Set of written software instructions' },
      eu: { clue: 'Softwareko idatzitako instrukzio-multzoa' } },
    { word: 'TECLADO', display: 'teclado', category: 'tecnologia', emoji: '⌨️',
      es: { clue: 'Dispositivo de entrada de texto' },
      en: { clue: 'Text input device' },
      eu: { clue: 'Testua sartzeko gailua' } },
    { word: 'MONITOR', display: 'monitor', category: 'tecnologia', emoji: '🖥️',
      es: { clue: 'Pantalla de visualización del ordenador' },
      en: { clue: 'Computer display screen' },
      eu: { clue: 'Ordenagailuaren bistaratzeko pantaila' } },
    { word: 'CHIP', display: 'chip', category: 'tecnologia', emoji: '🔧',
      es: { clue: 'Circuito integrado diminuto' },
      en: { clue: 'Tiny integrated circuit' },
      eu: { clue: 'Zirkuitu integratua txikia' } },
    { word: 'SATELITE', display: 'satélite', category: 'tecnologia', emoji: '🛰️',
      es: { clue: 'Dispositivo orbital de comunicaciones' },
      en: { clue: 'Orbital communications device' },
      eu: { clue: 'Komunikazio-gailua orbitala' } },
    { word: 'SENSOR', display: 'sensor', category: 'tecnologia', emoji: '📡',
      es: { clue: 'Dispositivo que detecta cambios físicos' },
      en: { clue: 'Device that detects physical changes' },
      eu: { clue: 'Aldaketa fisikoak detektatzen dituen gailua' } },
    { word: 'BATERIA', display: 'batería', category: 'tecnologia', emoji: '🔋',
      es: { clue: 'Dispositivo que almacena energía eléctrica' },
      en: { clue: 'Device that stores electrical energy' },
      eu: { clue: 'Energia elektrikoa gordetzen duen gailua' } },

    // ── NATURALEZA ────────────────────────────────────────────
    { word: 'BOSQUE', display: 'bosque', category: 'naturaleza', emoji: '🌲',
      es: { clue: 'Zona extensa cubierta de árboles' },
      en: { clue: 'Large area covered with trees' },
      eu: { clue: 'Zuhaitzez estalitako eremu zabala' } },
    { word: 'SELVA', display: 'selva', category: 'naturaleza', emoji: '🌴',
      es: { clue: 'Bosque tropical muy denso y húmedo' },
      en: { clue: 'Very dense and humid tropical forest' },
      eu: { clue: 'Oihan tropikala oso trinkoa eta hezea' } },
    { word: 'DESIERTO', display: 'desierto', category: 'naturaleza', emoji: '🏜️',
      es: { clue: 'Zona árida con escasas precipitaciones' },
      en: { clue: 'Arid area with scarce rainfall' },
      eu: { clue: 'Prezipitazio gutxiko eremu lehorra' } },
    { word: 'TUNDRA', display: 'tundra', category: 'naturaleza', emoji: '❄️',
      es: { clue: 'Bioma frío sin árboles del Ártico' },
      en: { clue: 'Cold treeless Arctic biome' },
      eu: { clue: 'Arktikoko bioma hotz eta zuhaitz gabea' } },
    { word: 'SABANA', display: 'sabana', category: 'naturaleza', emoji: '🌿',
      es: { clue: 'Pradera tropical con árboles dispersos' },
      en: { clue: 'Tropical grassland with scattered trees' },
      eu: { clue: 'Zuhaitz sakabanatutako belardi tropikala' } },
    { word: 'ARRECIFE', display: 'arrecife', category: 'naturaleza', emoji: '🐚',
      es: { clue: 'Ecosistema marino de coral' },
      en: { clue: 'Coral marine ecosystem' },
      eu: { clue: 'Koralezko itsas ekosistema' } },
    { word: 'VOLCAN', display: 'volcán', category: 'naturaleza', emoji: '🌋',
      es: { clue: 'Montaña que expulsa lava y gases' },
      en: { clue: 'Mountain that expels lava and gases' },
      eu: { clue: 'Laba eta gasak igortzen dituen mendia' } },
    { word: 'TERREMOTO', display: 'terremoto', category: 'naturaleza', emoji: '🌍',
      es: { clue: 'Temblor súbito de la corteza terrestre' },
      en: { clue: 'Sudden shaking of the Earth\'s crust' },
      eu: { clue: 'Lur-azalaren bat-bateko ikara' } },
    { word: 'TSUNAMI', display: 'tsunami', category: 'naturaleza', emoji: '🌊',
      es: { clue: 'Ola gigante causada por sismo marino' },
      en: { clue: 'Giant wave caused by sea earthquake' },
      eu: { clue: 'Itsasoko lurrikarak eragindako olatu erraldoia' } },
    { word: 'LLUVIA', display: 'lluvia', category: 'naturaleza', emoji: '🌧️',
      es: { clue: 'Precipitación de agua desde las nubes' },
      en: { clue: 'Water falling from clouds' },
      eu: { clue: 'Hodietatik erortzen den ura' } },
    { word: 'NIEVE', display: 'nieve', category: 'naturaleza', emoji: '❄️',
      es: { clue: 'Precipitación sólida de agua congelada' },
      en: { clue: 'Solid precipitation of frozen water' },
      eu: { clue: 'Ur izoztutako prezipitazio solidoa' } },
    { word: 'GRANIZO', display: 'granizo', category: 'naturaleza', emoji: '🌨️',
      es: { clue: 'Precipitación en forma de bolas de hielo' },
      en: { clue: 'Precipitation in the form of ice balls' },
      eu: { clue: 'Izotz-pilotan jaisten den prezipitazioa' } },
    { word: 'TORNADO', display: 'tornado', category: 'naturaleza', emoji: '🌪️',
      es: { clue: 'Columna de viento que gira violentamente' },
      en: { clue: 'Violently rotating column of wind' },
      eu: { clue: 'Bortizki biratzen den haize-zutabea' } },
    { word: 'RAYO', display: 'rayo', category: 'naturaleza', emoji: '⚡',
      es: { clue: 'Descarga eléctrica entre nube y tierra' },
      en: { clue: 'Electric discharge between cloud and ground' },
      eu: { clue: 'Hodeiaren eta lurraren arteko deskarga elektrikoa' } },
    { word: 'HURACANE', display: 'huracán', category: 'naturaleza', emoji: '🌀',
      es: { clue: 'Ciclón tropical de gran potencia' },
      en: { clue: 'Very powerful tropical cyclone' },
      eu: { clue: 'Potentzia handiko zikloi tropikala' } },

    // ── COMIDA ────────────────────────────────────────────────
    { word: 'PIZZA', display: 'pizza', category: 'comida', emoji: '🍕',
      es: { clue: 'Disco de masa con tomate y queso' },
      en: { clue: 'Dough disc with tomato and cheese' },
      eu: { clue: 'Tomatea eta gazta duen irin-disko' } },
    { word: 'PASTA', display: 'pasta', category: 'comida', emoji: '🍝',
      es: { clue: 'Alimento italiano de harina y agua' },
      en: { clue: 'Italian food made from flour and water' },
      eu: { clue: 'Irin eta urez egindako janari italiar' } },
    { word: 'ARROZ', display: 'arroz', category: 'comida', emoji: '🍚',
      es: { clue: 'Cereal base de la dieta asiática' },
      en: { clue: 'Grain that is the base of Asian diet' },
      eu: { clue: 'Asiako dieta-oinarrizko zerealea' } },
    { word: 'SUSHI', display: 'sushi', category: 'comida', emoji: '🍣',
      es: { clue: 'Plato japonés de arroz y pescado crudo' },
      en: { clue: 'Japanese dish of rice and raw fish' },
      eu: { clue: 'Arrozez eta arrain gordinaz egindako plater japoniar' } },
    { word: 'TACOS', display: 'tacos', category: 'comida', emoji: '🌮',
      es: { clue: 'Tortilla mexicana rellena de carne' },
      en: { clue: 'Mexican tortilla filled with meat' },
      eu: { clue: 'Haragiz betetako tortilla mexikarra' } },
    { word: 'PAELLA', display: 'paella', category: 'comida', emoji: '🥘',
      es: { clue: 'Plato valenciano de arroz y marisco' },
      en: { clue: 'Valencian rice and seafood dish' },
      eu: { clue: 'Arroz eta itsaskiz egindako Valentziako plater' } },
    { word: 'GAZPACHO', display: 'gazpacho', category: 'comida', emoji: '🍅',
      es: { clue: 'Sopa fría andaluza de tomate' },
      en: { clue: 'Cold Andalusian tomato soup' },
      eu: { clue: 'Tomatezko Andaluziako zopa hotza' } },
    { word: 'TORTILLA', display: 'tortilla', category: 'comida', emoji: '🥚',
      es: { clue: 'Preparado de huevo frito o con patata' },
      en: { clue: 'Fried egg preparation or with potato' },
      eu: { clue: 'Arrautza frijitua edo patatarekiko prestaketa' } },
    { word: 'QUESO', display: 'queso', category: 'comida', emoji: '🧀',
      es: { clue: 'Alimento lácteo fermentado sólido' },
      en: { clue: 'Solid fermented dairy food' },
      eu: { clue: 'Esnekia solidoa hartzitua' } },
    { word: 'JAMON', display: 'jamón', category: 'comida', emoji: '🍖',
      es: { clue: 'Pierna de cerdo curada o cocida' },
      en: { clue: 'Cured or cooked leg of pork' },
      eu: { clue: 'Txerri-hanka ondu edo egosita' } },
    { word: 'SALMON', display: 'salmón', category: 'comida', emoji: '🐟',
      es: { clue: 'Pez rosado muy apreciado en gastronomía' },
      en: { clue: 'Pink fish highly valued in gastronomy' },
      eu: { clue: 'Gastronomian oso baloratutako arrain arrosakara' } },
    { word: 'ATUN', display: 'atún', category: 'comida', emoji: '🐠',
      es: { clue: 'Gran pez marino de carne oscura' },
      en: { clue: 'Large sea fish with dark flesh' },
      eu: { clue: 'Haragi iluneko itsas arrain handia' } },
    { word: 'MIEL', display: 'miel', category: 'comida', emoji: '🍯',
      es: { clue: 'Líquido dulce producido por las abejas' },
      en: { clue: 'Sweet liquid produced by bees' },
      eu: { clue: 'Erleek ekoiztutako likido gozoa' } },
    { word: 'CANELA', display: 'canela', category: 'comida', emoji: '🌿',
      es: { clue: 'Especia aromática de corteza de árbol' },
      en: { clue: 'Aromatic spice from tree bark' },
      eu: { clue: 'Zuhaitz-azaletik hartutako espezia usaintsu' } },
    { word: 'OREGANO', display: 'orégano', category: 'comida', emoji: '🌿',
      es: { clue: 'Hierba aromática mediterránea' },
      en: { clue: 'Aromatic Mediterranean herb' },
      eu: { clue: 'Itsaso Ertaineko belar usaintsua' } },

    // ── VERBOS ────────────────────────────────────────────────
    { word: 'CORRER', display: 'correr', category: 'verbos', emoji: '🏃',
      es: { clue: 'Desplazarse a pie rápidamente' },
      en: { clue: 'To move on foot quickly' },
      eu: { clue: 'Oinez azkar mugitzea' } },
    { word: 'SALTAR', display: 'saltar', category: 'verbos', emoji: '🦘',
      es: { clue: 'Elevarse del suelo con impulso' },
      en: { clue: 'To rise from the ground with a jump' },
      eu: { clue: 'Lurretik altxatzea jauziz' } },
    { word: 'NADAR', display: 'nadar', category: 'verbos', emoji: '🏊',
      es: { clue: 'Desplazarse en el agua con el cuerpo' },
      en: { clue: 'To move through water using the body' },
      eu: { clue: 'Uran gorputzaz mugitzea' } },
    { word: 'CANTAR', display: 'cantar', category: 'verbos', emoji: '🎤',
      es: { clue: 'Emitir sonidos musicales con la voz' },
      en: { clue: 'To produce musical sounds with the voice' },
      eu: { clue: 'Ahotsez musika-soinuak sortzea' } },
    { word: 'BAILAR', display: 'bailar', category: 'verbos', emoji: '💃',
      es: { clue: 'Moverse al ritmo de la música' },
      en: { clue: 'To move to the rhythm of music' },
      eu: { clue: 'Musikaren erritmora mugitzea' } },
    { word: 'ESCRIBIR', display: 'escribir', category: 'verbos', emoji: '✍️',
      es: { clue: 'Representar palabras con signos gráficos' },
      en: { clue: 'To represent words with graphic signs' },
      eu: { clue: 'Hitzak ikur grafikoekin adieraztea' } },
    { word: 'COCINAR', display: 'cocinar', category: 'verbos', emoji: '👨‍🍳',
      es: { clue: 'Preparar alimentos aplicando calor' },
      en: { clue: 'To prepare food by applying heat' },
      eu: { clue: 'Beroa aplikatuz elikagaiak prestatzea' } },
    { word: 'ESTUDIAR', display: 'estudiar', category: 'verbos', emoji: '📚',
      es: { clue: 'Aprender algo a través del análisis' },
      en: { clue: 'To learn something through analysis' },
      eu: { clue: 'Zerbait azterketaren bidez ikastea' } },
    { word: 'PINTAR', display: 'pintar', category: 'verbos', emoji: '🎨',
      es: { clue: 'Aplicar color sobre una superficie' },
      en: { clue: 'To apply colour to a surface' },
      eu: { clue: 'Gainazal bati kolorea aplikatzea' } },
    { word: 'CREAR', display: 'crear', category: 'verbos', emoji: '✨',
      es: { clue: 'Producir algo nuevo desde la nada' },
      en: { clue: 'To produce something new from nothing' },
      eu: { clue: 'Ezetik zerbait berria sortzea' } },
    { word: 'VOLAR', display: 'volar', category: 'verbos', emoji: '✈️',
      es: { clue: 'Desplazarse por el aire' },
      en: { clue: 'To move through the air' },
      eu: { clue: 'Airean mugitzea' } },
    { word: 'AMAR', display: 'amar', category: 'verbos', emoji: '❤️',
      es: { clue: 'Sentir amor profundo por alguien' },
      en: { clue: 'To feel deep love for someone' },
      eu: { clue: 'Norbaiten aldeko maitasun sakona sentitzea' } },
    { word: 'SONAR', display: 'soñar', category: 'verbos', emoji: '💭',
      es: { clue: 'Tener imágenes mentales al dormir' },
      en: { clue: 'To have mental images while sleeping' },
      eu: { clue: 'Lo egitean buruko irudiak izatea' } },
    { word: 'TREPAR', display: 'trepar', category: 'verbos', emoji: '🧗',
      es: { clue: 'Subir usando manos y pies' },
      en: { clue: 'To climb using hands and feet' },
      eu: { clue: 'Esku eta oinak erabiliz igotzea' } },
    { word: 'BUCEAR', display: 'bucear', category: 'verbos', emoji: '🤿',
      es: { clue: 'Sumergirse y moverse bajo el agua' },
      en: { clue: 'To submerge and move underwater' },
      eu: { clue: 'Urpean sartu eta mugitzea' } },
];
