/**
 * GeoQuiz - Geographic Data
 * level: 1=easy 2=medium 3=hard
 */
const GQ_DATA = {

// ── WORLD COUNTRIES ── [{name, nameEn, capital, continent, flag, level}]
countries: [
  {name:'España',        nameEn:'Spain',          capital:'Madrid',               continent:'Europa',          flag:'🇪🇸', level:1},
  {name:'Francia',       nameEn:'France',          capital:'París',                continent:'Europa',          flag:'🇫🇷', level:1},
  {name:'Alemania',      nameEn:'Germany',         capital:'Berlín',               continent:'Europa',          flag:'🇩🇪', level:1},
  {name:'Italia',        nameEn:'Italy',           capital:'Roma',                 continent:'Europa',          flag:'🇮🇹', level:1},
  {name:'Portugal',      nameEn:'Portugal',        capital:'Lisboa',               continent:'Europa',          flag:'🇵🇹', level:1},
  {name:'Reino Unido',   nameEn:'United Kingdom',  capital:'Londres',              continent:'Europa',          flag:'🇬🇧', level:1},
  {name:'Estados Unidos',nameEn:'USA',             capital:'Washington D.C.',      continent:'América del Norte',flag:'🇺🇸', level:1},
  {name:'México',        nameEn:'Mexico',          capital:'Ciudad de México',     continent:'América del Norte',flag:'🇲🇽', level:1},
  {name:'Brasil',        nameEn:'Brazil',          capital:'Brasilia',             continent:'América del Sur', flag:'🇧🇷', level:1},
  {name:'Argentina',     nameEn:'Argentina',       capital:'Buenos Aires',         continent:'América del Sur', flag:'🇦🇷', level:1},
  {name:'China',         nameEn:'China',           capital:'Pekín',                continent:'Asia',            flag:'🇨🇳', level:1},
  {name:'Japón',         nameEn:'Japan',           capital:'Tokio',                continent:'Asia',            flag:'🇯🇵', level:1},
  {name:'Rusia',         nameEn:'Russia',          capital:'Moscú',                continent:'Europa/Asia',     flag:'🇷🇺', level:1},
  {name:'Australia',     nameEn:'Australia',       capital:'Canberra',             continent:'Oceanía',         flag:'🇦🇺', level:1},
  {name:'India',         nameEn:'India',           capital:'Nueva Delhi',          continent:'Asia',            flag:'🇮🇳', level:1},
  {name:'Canadá',        nameEn:'Canada',          capital:'Ottawa',               continent:'América del Norte',flag:'🇨🇦', level:2},
  {name:'Egipto',        nameEn:'Egypt',           capital:'El Cairo',             continent:'África',          flag:'🇪🇬', level:2},
  {name:'Sudáfrica',     nameEn:'South Africa',    capital:'Pretoria',             continent:'África',          flag:'🇿🇦', level:2},
  {name:'Marruecos',     nameEn:'Morocco',         capital:'Rabat',                continent:'África',          flag:'🇲🇦', level:2},
  {name:'Nigeria',       nameEn:'Nigeria',         capital:'Abuja',                continent:'África',          flag:'🇳🇬', level:2},
  {name:'Bélgica',       nameEn:'Belgium',         capital:'Bruselas',             continent:'Europa',          flag:'🇧🇪', level:2},
  {name:'Países Bajos',  nameEn:'Netherlands',     capital:'Ámsterdam',            continent:'Europa',          flag:'🇳🇱', level:2},
  {name:'Suiza',         nameEn:'Switzerland',     capital:'Berna',                continent:'Europa',          flag:'🇨🇭', level:2},
  {name:'Grecia',        nameEn:'Greece',          capital:'Atenas',               continent:'Europa',          flag:'🇬🇷', level:2},
  {name:'Turquía',       nameEn:'Turkey',          capital:'Ankara',               continent:'Europa/Asia',     flag:'🇹🇷', level:2},
  {name:'Colombia',      nameEn:'Colombia',        capital:'Bogotá',               continent:'América del Sur', flag:'🇨🇴', level:2},
  {name:'Chile',         nameEn:'Chile',           capital:'Santiago',             continent:'América del Sur', flag:'🇨🇱', level:2},
  {name:'Indonesia',     nameEn:'Indonesia',       capital:'Yakarta',              continent:'Asia',            flag:'🇮🇩', level:2},
  {name:'Corea del Sur', nameEn:'South Korea',     capital:'Seúl',                 continent:'Asia',            flag:'🇰🇷', level:2},
  {name:'Arabia Saudí',  nameEn:'Saudi Arabia',    capital:'Riad',                 continent:'Asia',            flag:'🇸🇦', level:2},
  {name:'Polonia',       nameEn:'Poland',          capital:'Varsovia',             continent:'Europa',          flag:'🇵🇱', level:2},
  {name:'Suecia',        nameEn:'Sweden',          capital:'Estocolmo',            continent:'Europa',          flag:'🇸🇪', level:2},
  {name:'Noruega',       nameEn:'Norway',          capital:'Oslo',                 continent:'Europa',          flag:'🇳🇴', level:2},
  {name:'Irlanda',       nameEn:'Ireland',         capital:'Dublín',               continent:'Europa',          flag:'🇮🇪', level:2},
  {name:'Irán',          nameEn:'Iran',            capital:'Teherán',              continent:'Asia',            flag:'🇮🇷', level:3},
  {name:'Pakistán',      nameEn:'Pakistan',        capital:'Islamabad',            continent:'Asia',            flag:'🇵🇰', level:3},
  {name:'Perú',          nameEn:'Peru',            capital:'Lima',                 continent:'América del Sur', flag:'🇵🇪', level:3},
  {name:'Venezuela',     nameEn:'Venezuela',       capital:'Caracas',              continent:'América del Sur', flag:'🇻🇪', level:3},
  {name:'Vietnam',       nameEn:'Vietnam',         capital:'Hanói',                continent:'Asia',            flag:'🇻🇳', level:3},
  {name:'Filipinas',     nameEn:'Philippines',     capital:'Manila',               continent:'Asia',            flag:'🇵🇭', level:3},
  {name:'Kenia',         nameEn:'Kenya',           capital:'Nairobi',              continent:'África',          flag:'🇰🇪', level:3},
  {name:'Cuba',          nameEn:'Cuba',            capital:'La Habana',            continent:'América',         flag:'🇨🇺', level:3},
  {name:'Nueva Zelanda', nameEn:'New Zealand',     capital:'Wellington',           continent:'Oceanía',         flag:'🇳🇿', level:3},
  {name:'Israel',        nameEn:'Israel',          capital:'Jerusalén',            continent:'Asia',            flag:'🇮🇱', level:3},
],

// ── WORLD RIVERS ── [{name, region, km, level}]
world_rivers: [
  {name:'Nilo',       region:'África',          km:6650, info:'Río más largo del mundo', level:1},
  {name:'Amazonas',   region:'América del Sur', km:6400, info:'Mayor caudal del mundo',  level:1},
  {name:'Yangtsé',    region:'China',           km:6300, info:'Río más largo de Asia',    level:1},
  {name:'Misisipi',   region:'Estados Unidos',  km:6275, info:'Río más largo de Norteamérica', level:1},
  {name:'Volga',      region:'Rusia',           km:3690, info:'Río más largo de Europa',  level:1},
  {name:'Congo',      region:'África Central',  km:4700, info:'Segundo mayor caudal',     level:2},
  {name:'Mekong',     region:'Asia SE',         km:4350, info:'Atraviesa 6 países asiáticos', level:2},
  {name:'Níger',      region:'África Oeste',    km:4180, info:'Tercer río más largo de África', level:2},
  {name:'Danubio',    region:'Europa Central',  km:2860, info:'Segundo río más largo de Europa', level:2},
  {name:'Ganges',     region:'India',           km:2525, info:'Río sagrado de la India',  level:2},
  {name:'Zambeze',    region:'África Sur',      km:2574, info:'Cataratas Victoria',       level:2},
  {name:'Orinoco',    region:'Venezuela',       km:2140, info:'Gran río sudamericano',    level:2},
  {name:'Rin',        region:'Europa Oeste',    km:1230, info:'Río industrial de Europa', level:2},
  {name:'Ob',         region:'Rusia',           km:5410, info:'Gran río siberiano',       level:3},
  {name:'Yeniséi',    region:'Rusia',           km:5539, info:'Río más caudaloso de Rusia', level:3},
  {name:'Lena',       region:'Rusia',           km:4400, info:'Río del permafrost siberiano', level:3},
  {name:'Mackenzie',  region:'Canadá',          km:4241, info:'Río más largo de Canadá',  level:3},
  {name:'Tigris',     region:'Oriente Medio',   km:1950, info:'Mesopotamia, junto al Éufrates', level:3},
],

// ── WORLD MOUNTAINS ── [{name, region, height, level}]
world_mountains: [
  {name:'Everest',        region:'Nepal/China',    height:8849, info:'Cumbre más alta del mundo', level:1},
  {name:'Aconcagua',      region:'Argentina',      height:6961, info:'Más alto de América',       level:1},
  {name:'Kilimanjaro',    region:'Tanzania',       height:5895, info:'Más alto de África',        level:1},
  {name:'Mont Blanc',     region:'Francia/Italia', height:4808, info:'Más alto de los Alpes',     level:1},
  {name:'K2',             region:'Pakistán/China', height:8611, info:'Segunda cumbre más alta',   level:2},
  {name:'Elbrus',         region:'Rusia',          height:5642, info:'Más alto de Europa',        level:2},
  {name:'Denali',         region:'Alaska, EEUU',   height:6190, info:'Más alto de América del Norte', level:2},
  {name:'Mauna Kea',      region:'Hawái, EEUU',    height:4205, info:'Más alto desde el fondo marino', level:2},
  {name:'Kangchenjunga',  region:'Nepal/India',    height:8586, info:'Tercera cumbre más alta',   level:3},
  {name:'Annapurna',      region:'Nepal',          height:8091, info:'Décima cumbre más alta',    level:3},
  {name:'Vinson',         region:'Antártida',      height:4892, info:'Más alto de la Antártida',  level:3},
  {name:'Puncak Jaya',    region:'Indonesia',      height:4884, info:'Más alto de Oceanía',       level:3},
],

// ── SPAIN COMUNIDADES ── [{name, capital, level}]
comunidades: [
  {name:'Andalucía',              capital:'Sevilla',                  level:1},
  {name:'Aragón',                 capital:'Zaragoza',                 level:1},
  {name:'Asturias',               capital:'Oviedo',                   level:1},
  {name:'Islas Baleares',         capital:'Palma',                    level:1},
  {name:'Canarias',               capital:'Las Palmas / Santa Cruz',  level:1},
  {name:'Cantabria',              capital:'Santander',                level:1},
  {name:'Castilla-La Mancha',     capital:'Toledo',                   level:1},
  {name:'Castilla y León',        capital:'Valladolid',               level:1},
  {name:'Cataluña',               capital:'Barcelona',                level:1},
  {name:'Extremadura',            capital:'Mérida',                   level:2},
  {name:'Galicia',                capital:'Santiago de Compostela',   level:1},
  {name:'La Rioja',               capital:'Logroño',                  level:2},
  {name:'Comunidad de Madrid',    capital:'Madrid',                   level:1},
  {name:'Región de Murcia',       capital:'Murcia',                   level:2},
  {name:'Navarra',                capital:'Pamplona',                 level:2},
  {name:'País Vasco',             capital:'Vitoria-Gasteiz',          level:1},
  {name:'Comunidad Valenciana',   capital:'Valencia',                 level:1},
],

// ── SPAIN PROVINCIAS ── [{name, capital, comunidad, level}]
provincias: [
  {name:'Almería',     capital:'Almería',     comunidad:'Andalucía',           level:2},
  {name:'Cádiz',       capital:'Cádiz',       comunidad:'Andalucía',           level:2},
  {name:'Córdoba',     capital:'Córdoba',     comunidad:'Andalucía',           level:1},
  {name:'Granada',     capital:'Granada',     comunidad:'Andalucía',           level:1},
  {name:'Huelva',      capital:'Huelva',      comunidad:'Andalucía',           level:2},
  {name:'Jaén',        capital:'Jaén',        comunidad:'Andalucía',           level:2},
  {name:'Málaga',      capital:'Málaga',      comunidad:'Andalucía',           level:1},
  {name:'Sevilla',     capital:'Sevilla',     comunidad:'Andalucía',           level:1},
  {name:'Huesca',      capital:'Huesca',      comunidad:'Aragón',              level:2},
  {name:'Teruel',      capital:'Teruel',      comunidad:'Aragón',              level:2},
  {name:'Zaragoza',    capital:'Zaragoza',    comunidad:'Aragón',              level:1},
  {name:'Asturias',    capital:'Oviedo',      comunidad:'Asturias',            level:2},
  {name:'Baleares',    capital:'Palma',       comunidad:'Islas Baleares',      level:2},
  {name:'Las Palmas',  capital:'Las Palmas',  comunidad:'Canarias',            level:2},
  {name:'Santa Cruz',  capital:'Santa Cruz de Tenerife', comunidad:'Canarias', level:2},
  {name:'Cantabria',   capital:'Santander',   comunidad:'Cantabria',           level:2},
  {name:'Albacete',    capital:'Albacete',    comunidad:'Castilla-La Mancha',  level:2},
  {name:'Ciudad Real', capital:'Ciudad Real', comunidad:'Castilla-La Mancha',  level:2},
  {name:'Cuenca',      capital:'Cuenca',      comunidad:'Castilla-La Mancha',  level:3},
  {name:'Guadalajara', capital:'Guadalajara', comunidad:'Castilla-La Mancha',  level:3},
  {name:'Toledo',      capital:'Toledo',      comunidad:'Castilla-La Mancha',  level:2},
  {name:'Ávila',       capital:'Ávila',       comunidad:'Castilla y León',     level:2},
  {name:'Burgos',      capital:'Burgos',      comunidad:'Castilla y León',     level:2},
  {name:'León',        capital:'León',        comunidad:'Castilla y León',     level:2},
  {name:'Palencia',    capital:'Palencia',    comunidad:'Castilla y León',     level:3},
  {name:'Salamanca',   capital:'Salamanca',   comunidad:'Castilla y León',     level:2},
  {name:'Segovia',     capital:'Segovia',     comunidad:'Castilla y León',     level:2},
  {name:'Soria',       capital:'Soria',       comunidad:'Castilla y León',     level:3},
  {name:'Valladolid',  capital:'Valladolid',  comunidad:'Castilla y León',     level:2},
  {name:'Zamora',      capital:'Zamora',      comunidad:'Castilla y León',     level:3},
  {name:'Barcelona',   capital:'Barcelona',   comunidad:'Cataluña',            level:1},
  {name:'Girona',      capital:'Girona',      comunidad:'Cataluña',            level:2},
  {name:'Lleida',      capital:'Lleida',      comunidad:'Cataluña',            level:3},
  {name:'Tarragona',   capital:'Tarragona',   comunidad:'Cataluña',            level:2},
  {name:'Badajoz',     capital:'Badajoz',     comunidad:'Extremadura',         level:2},
  {name:'Cáceres',     capital:'Cáceres',     comunidad:'Extremadura',         level:2},
  {name:'A Coruña',    capital:'A Coruña',    comunidad:'Galicia',             level:2},
  {name:'Lugo',        capital:'Lugo',        comunidad:'Galicia',             level:3},
  {name:'Ourense',     capital:'Ourense',     comunidad:'Galicia',             level:3},
  {name:'Pontevedra',  capital:'Pontevedra',  comunidad:'Galicia',             level:2},
  {name:'La Rioja',    capital:'Logroño',     comunidad:'La Rioja',            level:2},
  {name:'Madrid',      capital:'Madrid',      comunidad:'Comunidad de Madrid', level:1},
  {name:'Murcia',      capital:'Murcia',      comunidad:'Región de Murcia',    level:2},
  {name:'Navarra',     capital:'Pamplona',    comunidad:'Navarra',             level:2},
  {name:'Álava',       capital:'Vitoria-Gasteiz',    comunidad:'País Vasco',   level:2},
  {name:'Gipuzkoa',    capital:'Donostia-San Sebastián', comunidad:'País Vasco', level:2},
  {name:'Bizkaia',     capital:'Bilbao',      comunidad:'País Vasco',          level:2},
  {name:'Alicante',    capital:'Alicante',    comunidad:'Comunidad Valenciana', level:2},
  {name:'Castellón',   capital:'Castellón',   comunidad:'Comunidad Valenciana', level:2},
  {name:'Valencia',    capital:'Valencia',    comunidad:'Comunidad Valenciana', level:1},
],

// ── SPAIN RIVERS ── [{name, origin, mouth, km, level}]
spain_rivers: [
  {name:'Ebro',          origin:'Cantabria',          mouth:'Mediterráneo (Tarragona)', km:930,  level:1},
  {name:'Tajo',          origin:'Montes Universales',  mouth:'Atlántico (Lisboa)',       km:1007, level:1},
  {name:'Duero',         origin:'Picos de Urbión',     mouth:'Atlántico (Oporto)',       km:897,  level:1},
  {name:'Guadalquivir',  origin:'Sierra de Cazorla',   mouth:'Atlántico (Huelva)',       km:657,  level:1},
  {name:'Guadiana',      origin:'Ruidera (La Mancha)', mouth:'Atlántico (Huelva)',       km:744,  level:2},
  {name:'Miño',          origin:'Fuente Miña (Lugo)',  mouth:'Atlántico (Pontevedra)',   km:340,  level:2},
  {name:'Júcar',         origin:'Montes Universales',  mouth:'Mediterráneo (Valencia)',  km:498,  level:2},
  {name:'Segura',        origin:'Sierra de Segura',    mouth:'Mediterráneo (Murcia)',    km:325,  level:2},
  {name:'Turia',         origin:'Montes Universales',  mouth:'Mediterráneo (Valencia)',  km:280,  level:3},
  {name:'Genil',         origin:'Sierra Nevada',       mouth:'Guadalquivir (Córdoba)',   km:358,  level:2},
  {name:'Pisuerga',      origin:'Picos de Europa',     mouth:'Duero (Valladolid)',       km:280,  level:3},
  {name:'Nalón',         origin:'Alto Pajares',        mouth:'Atlántico (Asturias)',     km:145,  level:3},
],

// ── SPAIN MOUNTAINS ── [{name, height, province, comunidad, level}]
spain_mountains: [
  {name:'Teide',           height:3715, province:'Sta. Cruz de Tenerife', comunidad:'Canarias',        level:1},
  {name:'Mulhacén',        height:3479, province:'Granada',               comunidad:'Andalucía',       level:1},
  {name:'Aneto',           height:3404, province:'Huesca',                comunidad:'Aragón',          level:1},
  {name:'Veleta',          height:3396, province:'Granada',               comunidad:'Andalucía',       level:2},
  {name:'Monte Perdido',   height:3355, province:'Huesca',                comunidad:'Aragón',          level:2},
  {name:'Torre Cerredo',   height:2650, province:'Asturias/León',         comunidad:'Picos de Europa', level:2},
  {name:'Pico Almanzor',   height:2592, province:'Ávila',                 comunidad:'Castilla y León', level:2},
  {name:'Peñalara',        height:2428, province:'Madrid/Segovia',        comunidad:'Sierra Guadarrama', level:3},
  {name:'Penyagolosa',     height:1813, province:'Castellón',             comunidad:'Comunidad Valenciana', level:3},
  {name:'Puig Major',      height:1445, province:'Baleares',              comunidad:'Islas Baleares',  level:3},
],

// ── EUSKADI TERRITORIES ── [{name, nameEu, capital, info}]
euskadi_territories: [
  {name:'Álava',      nameEu:'Araba',    capital:'Vitoria-Gasteiz',           info:'Territorio interior, capital del País Vasco'},
  {name:'Bizkaia',    nameEu:'Bizkaia',  capital:'Bilbao / Bilbo',            info:'Costa cantábrica, mayor población'},
  {name:'Gipuzkoa',   nameEu:'Gipuzkoa', capital:'Donostia-San Sebastián',   info:'Costa norte, Pintxos y Parte Vieja'},
],

// ── EUSKADI MUNICIPALITIES ── [{name, nameEu, territory, info, level}]
euskadi_munis: [
  {name:'Bilbao',              nameEu:'Bilbo',         territory:'Bizkaia',  info:'Mayor ciudad, Museo Guggenheim', level:1},
  {name:'Donostia-S.Sebastián',nameEu:'Donostia',      territory:'Gipuzkoa', info:'Playa de la Concha, festivals',  level:1},
  {name:'Vitoria-Gasteiz',     nameEu:'Gasteiz',       territory:'Álava',    info:'Capital política del País Vasco', level:1},
  {name:'Barakaldo',           nameEu:'Barakaldo',     territory:'Bizkaia',  info:'Gran Bilbao, zona industrial',   level:2},
  {name:'Getxo',               nameEu:'Getxo',         territory:'Bizkaia',  info:'Municipio costero del Gran Bilbao', level:2},
  {name:'Irun',                nameEu:'Irun',          territory:'Gipuzkoa', info:'Frontera con Francia',           level:2},
  {name:'Eibar',               nameEu:'Eibar',         territory:'Gipuzkoa', info:'Industria armera histórica',     level:2},
  {name:'Durango',             nameEu:'Durango',       territory:'Bizkaia',  info:'Capital de la Merindad de Durango', level:2},
  {name:'Mondragón',           nameEu:'Arrasate',      territory:'Gipuzkoa', info:'Corporación Mondragón, cooperativas', level:2},
  {name:'Bermeo',              nameEu:'Bermeo',        territory:'Bizkaia',  info:'Puerto pesquero histórico',      level:2},
  {name:'Zarautz',             nameEu:'Zarautz',       territory:'Gipuzkoa', info:'Playa y surf en la costa',       level:3},
  {name:'Tolosa',              nameEu:'Tolosa',        territory:'Gipuzkoa', info:'Capital histórica de Gipuzkoa',  level:3},
],

// ── EUSKADI RIVERS ── [{name, territory, km, level}]
euskadi_rivers: [
  {name:'Nervión',   territory:'Bizkaia/Álava',    km:72,  info:'Nace en Álava, desemboca en Bilbao', level:1},
  {name:'Oria',      territory:'Gipuzkoa',          km:80,  info:'Atraviesa Tolosa y Orio',            level:1},
  {name:'Urola',     territory:'Gipuzkoa',          km:58,  info:'Pasa por Azpeitia y Zumaia',         level:2},
  {name:'Deba',      territory:'Gipuzkoa/Álava',    km:67,  info:'Desemboca en Deba',                  level:2},
  {name:'Bidasoa',   territory:'Gipuzkoa/Navarra',  km:70,  info:'Frontera con Francia',               level:2},
  {name:'Zadorra',   territory:'Álava',             km:75,  info:'Embalse de Ullibarri',               level:2},
  {name:'Baias',     territory:'Álava',             km:57,  info:'Afluente del Ebro en Álava',         level:3},
],

// ── EUSKADI MOUNTAINS ── [{name, height, territory, level}]
euskadi_mountains: [
  {name:'Aizkorri',    height:1528, territory:'Gipuzkoa/Álava',  info:'Punto más alto de Gipuzkoa', level:1},
  {name:'Gorbea',      height:1482, territory:'Bizkaia/Álava',   info:'Símbolo del País Vasco',     level:1},
  {name:'Aratz',       height:1443, territory:'Gipuzkoa/Álava',  info:'Sierra de Aizkorri',         level:2},
  {name:'Anboto',      height:1331, territory:'Bizkaia',         info:'Leyenda de Mari',            level:2},
  {name:'Aralar',      height:1442, territory:'Gipuzkoa/Navarra',info:'Santuario de San Miguel',    level:2},
  {name:'Ganekogorta', height:1126, territory:'Bizkaia',         info:'Enclave Bizkaia-Álava',      level:2},
  {name:'Udalaitz',    height:1092, territory:'Bizkaia/Gipuzkoa',info:'Visión panorámica del Deba', level:2},
  {name:'Urkiola',     height:1083, territory:'Bizkaia',         info:'Parque natural',             level:2},
  {name:'Hernio',      height:1075, territory:'Gipuzkoa',        info:'Entre Orio y Deba',          level:3},
  {name:'Izarraitz',   height:1026, territory:'Gipuzkoa',        info:'Comarca del Urola Kosta',    level:3},
],

};
